language: python
python:
  - "3.6"
dist: trusty
sudo: required
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install .
cache: pip
script: .travis/run-tests.sh
