language: python
python:
  - "3.5"
  - "3.6"
dist: trusty
install:
    - pip install -r requirements.txt
    - pip install -r requirements-dev.txt
    - pip install src/nete-common
    - pip install src/nete-backend
    - pip install src/nete-cli
    - pip install pytest-cov
script:
    - .travis/run-tests.sh
after_success:
    - bash <(curl -s https://codecov.io/bash)
